### ISSUE TITLE
The close event was triggered before the file was written to disk

### ISSUE THREAD

**Issue by xianlong1226** [mhr3/unzip-stream#1]
I want to read the file after unzip, but it failed, because the file was not written to disk now.
The follow is my code:
let fs = require('fs');
let path = require('path');
let unzip = require('unzip-stream');

let input = fs.createReadStream('test.zip');
let output = unzip.Extract({ path: path.join(__dirname, 'unzip') });

output.on('close', function(){
    console.log('unzip close');
    let data = fs.readFileSync(path.join(__dirname, './unzip/paper.json'), 'utf8');
});
output.on('error', function(err){
    console.error(err.stack);
});

input.pipe(output);

**Comment by mhr3** [comment]
Did you try to use the finish event?

**Comment by xianlong1226** [comment]
yes,the same result.

**Comment by DaRich** [comment]
Same problem here. Want to change a file after unzip.
This file is not present when the close/finish event fires.

**Comment by kkogovsek** [comment]
Same problem here. Its critical in our application.

**Comment by mhr3** [comment]
unzip-stream is mostly focused on the `Parse()` codepath, I'm considering whether to remove `Extract` completely (which would simplify the package quite a lot) or try to fix it.

**Comment by mickeyjohn** [comment]
I have the same problem. The decompress folder and content is not exist when close or finish even emitted. Please please fix. You did a good job to fix the 'Invalid Signature' problem as being in unzip or unzip2.

Thanks alot in advance.
Cheers.

**Comment by mhr3** [comment]
I've just published 0.2.0, which should fix the problem (and yes, please use the `close` event, NOT `finish`)
