### ISSUE TITLE
On entry does not fire

### ISSUE THREAD

**Issue by 1Map** [mhr3/unzip-stream#16]
In the past (0.1.2) I used to have:

```
var unzipExtractor = unzip.Extract({
    path: workfolder
});

unzipExtractor.on('close', function () {
    // This line do fire
});

fs.createReadStream(myZipFile).pipe(unzipExtractor).on('entry', function (entry) {
    // Execute code for each entry - **THIS NEVER GETS EXECUTED - USED TO WORK IN 0.1.2**
});
```

This does not seem to work anymore.  Any idea why not?

**Comment by mhr3** [comment]
The `unzip.Extract()` destination does not indeed emit the "entry" event, as the individual file streams are already being extracted. If you wish to handle the extraction manually, you should use the `unzip.Parse()` method.

But you are right that upon successful completion, the close signal should be emitted, perhaps try connecting also to the 'error' event and check whether there's any errors.
