### ISSUE TITLE
After unzip, file lost exec permission. [MacOSX]

### ISSUE THREAD

**Issue by Eskibear** [mhr3/unzip-stream#18]
In the zip file, it has `x` permission, but without `x` permission after been extracted.

**Comment by mhr3** [comment]
Permissions are not preserved at the moment, as it isn't straight-forward when doing streaming.

**Comment by Eskibear** [comment]
So can I understand it as there would be no plan to support permission preservation?

**Comment by mhr3** [comment]
There will be an option for it in the future.

**Comment by Eskibear** [comment]
Thanks for your information, cannot wait for it, so I've changed to use `extract-zip` for the moment.
