### ISSUE TITLE
Extract Method cannot allow passing decodeString property

### ISSUE THREAD

**Issue by poryzhao** [mhr3/unzip-stream#30]
I try to pass decodeString property to Extract method like this:

`fs.createReadStream(file.filepath)`
` .pipe(unzip.Extract({`
`decodeString: (buffer) => { return iconvLite.decode(buffer, 'UTF-8'); },`
`path: zipFilePath,`
`}))`

But it doesnot work. After I review the source code, I found in the Extract function, when try to new UnzipStream, the param opts is forgotten to pass：
`this.unzipStream = new UnzipStream(this.opts);`

**Comment by mhr3** [comment]
Fixed via 64c7dff37279b79a9e8956794b93479cb1992be0
