### ISSUE TITLE
Support passing file comments through for each entry

### ISSUE THREAD

**Issue by ralbayaty** [mhr3/unzip-stream#35]
Both `CENTRAL_DIRECTORY_FILE_HEADER` and `CENTRAL_DIRECTORY_END_COMMENT` are read but many properties are not passed to the entries. Things like the file comment are added to `parsedEntity.extra` but they are not exposed through `UnzipStream.prototype._prepareOutStream`. Using unzip.Parse({ debug: true }) shows them through stdout of course.

~~I was thinking to start a PR for this as it appears to be a few LOC to add. That being said, I'm not sure how this will impact the tests and will need to dig there.~~

**Comment by mhr3** [comment]
The zip central directory is basically ignored, as a streaming unzip only the local headers are needed.

Long time ago I was thinking about a v2 of the package which would emit some kind of `metadata` after all the entries, which would allow supporting symlinks etc, feels like this would fit into that quite well. Then again, v2 wasn't started yet.

**Comment by ralbayaty** [comment]
So are you suggesting this is something `unzip-stream` should not support? Just curious why the comments are not passed through if accessible.

**Comment by mhr3** [comment]
The central directory is located at the end of the stream, ie after all the files have been read, which means the comments aren't accessible while the individual entries are being processed.

**Comment by ralbayaty** [comment]
Closing this since really out of scope for a streaming unzip.
