### ISSUE TITLE
"Invalid signature" on null padding

### ISSUE THREAD

**Issue by tgvarik** [mhr3/unzip-stream#4]
The [PKZIP spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) forbids null padding, _inter alia_, **within** local file record sequences:
- between a local file header record and its accompanying encryption header record (if present)
- between a local file header record and its accompanying file data record (if no encryption header record is present)
- between an encryption header record (if present) and its accompanying file data record
- between a file data record and its accompanying data descriptor record (if present)

Interestingly, it does _not_ forbid null padding **between** such sequences.

I find myself sadly burdened with being required to deal with a lot of PKZIP files with null padding between local file record sequences on an ongoing basis for the foreseeable future. I have found that some PKZIP software (WinZip, Info-ZIP) handles these files easily, while other software (OS X, every PKZIP unzipper on npm) chokes and dies, including unzip-stream, which reports "Invalid signature in zip file".

It would make my life so, so much better if unzip-stream could support files with null padding between local file record sequences.

**Comment by mhr3** [comment]
Could you attach an example zip file which is using this pls?

**Comment by mhr3** [comment]
I've added something in 0.3.0 that should deal with the padding, mind giving it a go?
