### ISSUE TITLE
Total number of entries?

### ISSUE THREAD

**Issue by justinmchase** [mhr3/unzip-stream#40]
Is there a way to get the count of entries early in the stream processing?

Like could we emit a `'header'` event or is there a field which is being set that I'm not seeing?

Possibly this information is not knowable without iterating the stream, then oh well but if it is available early on in stream processing I'd be really interested in getting that count somehow for progress reporting.

**Comment by mhr3** [comment]
Nope, when processing zip as a stream you have to go through everything, as the "header" is at the very end of the stream.

**Comment by justinmchase** [comment]
Ok, thanks.
